export const ActionTypes = {
    FETCH_TRENDING_MOVIES : 'FETCH_TRENDING_MOVIES',
    FETCH_PLAYING_MOVIES : 'FETCH_PLAYING_MOVIES',
    FETCH_SERIES  : 'FETCH_SERIES',
    FETCH_GENRES : 'FETCH_GENRES',
    SELECT_MOVIE : 'SELECT_MOVIE',
    UNSELECT_MOVIE : 'UNSELECT_MOVIE'
};